### ISSUE TITLE
Python CLI and Module - pydispo

### ISSUE THREAD

**Issue by aakash30jan** [sdushantha/tmpmail#21]
Not exactly an issue, but reporting an additional feature/enhancement. 
Inspired by `tmpmail`, I have written a kind of pure-pythonic utility to perform similar tasks. Its called `pydispo` and you can find it at [https://github.com/aakash30jan/pydispo](https://github.com/aakash30jan/pydispo). I have tried making it platform-independent and almost without external dependencies, but tried keeping the similar usage pattern as `tmpmail`.
Thanks @sdushantha , I have already cited `tmpmail` on my repo.

**Comment by sdushantha** [comment]
@aakash30jan This is awesome! I initially created `tmpmail` in Python but then rewrote it in bash because I wanted to expand my bash scripting knowledge.

If I were you, I would post your project on [r/coolgithubprojects](https://www.reddit.com/r/coolgithubprojects), [r/Python](https://www.reddit.com/r/Python/), and  [r/madeinpython](https://www.reddit.com/r/madeinpython/) so that more people start using `pydispo` :)
