### ISSUE TITLE
allow passing username to generate function

### ISSUE THREAD

**Issue by zanona** [sdushantha/tmpmail#22]
Hi, thanks a lot for _tmpmail_. It's a breeze to use. :wink: 

Perhaps we could pass an argument to the generation function in order to access an inbox for an email we created in the past? _let's say, a login for a forum_

```
tmpmail --generate foobar
[ Inbox for foobar@1secmail.com ] 
```

At the moment I am editing the `/tmp/tmpmail/email_address` file to set it up.
I appreciate its good practice to keep those usernames random and unidentifiable but it's just in case you need to recover a password for a service or get any timely notification.

**Comment by sdushantha** [comment]
Thank you for you the issue. We've has this feature request brought up in #6 and #15, where I decided not to add this feature because the reason for why this functionality should be added was not convincing enough to me.

But your reason seems very reasonable:

> Perhaps we could pass an argument to the generation function in order to access an inbox for an email we created in the past? let's say, a login for a forum


I think we can use @anthonybaldwin's [method](https://github.com/sdushantha/tmpmail/pull/6/commits/1a3e9050c62680bbf8e5ae237f02572c22aa8ced#diff-d8a1c8fedc81914dd8f30442b657ae2fL277-R281) for implementing this feature

**Comment by zanona** [comment]
Thanks for following up so quickly :) 
That PR seems spot-on for me.

**Comment by sdushantha** [comment]
@zanona This feature has been added to the latest version of `tmpmail` 🎉

**Comment by zanona** [comment]
That's awesome!
There's even regexp validation with access or the .org,.net domains. That's even better than I expected. 
Thank you very much for your work. :)
