### ISSUE TITLE
Checking on the command syntax before changing the options/arguments code.

### ISSUE THREAD

**Issue by GReagle** [sdushantha/tmpmail#33]
I think that I can make improvements to the code that processes the arguments and options, both in terms of clarity/brevity as well as robustness (e.g. error checking for optional arguments).  I did a code change earlier that changed the syntax of the command, which was declined.  Before I do another change, I want to double check on the current syntax and semantics of the command.  This is my interpretation of how the command currently (or is supposed to) works.  Is it accurate?  Note that this is the output of a manpage that I wrote, and following manpage conventions, the brackets indicate optional and the pipe indicates xor.
```
NAME
     tmpmail — temporary mail

SYNOPSIS
     tmpmail
     tmpmail -h | --version
     tmpmail -g [ADDRESS]
     tmpmail [-t | -b BROWSER] -r | ID

OPTIONS
     -b | --browser BROWSER
             Specify BROWSER (default: w3m) that is used to render the HTML of
             the email

     -g | --generate [ADDRESS]
             Generate a new email address, either the specified ADDRESS, or
             randomly create one

     -h | --help
             Show help

     -r | --recent
             View the most recent email message

     -t | --text
             View the email as raw text, where all the HTML tags are removed
             (default: html)

     --version
             Show version

ARGUMENTS
     When called with no option and no argument, tmpmail lists the messages in
     the inbox and their numeric IDs.  When called with one argument, tmpmail
     shows the email message with specified ID.
```

**Comment by sdushantha** [comment]
This man page looks really good! I think your man page is much easier to understand compared to the `--help` output we currently have.

I do have some minor suggestions for the man page though.
Instead of separating the short command and the long command with a pipe, wouldn't it better to use a comma instead?
Regarding the `--text` flag, you added a small note where it says `(default: html)`. I find this a little misleading as it could indicate that `--text` by default has the value of `html`, but the user can change that by using `--text SOMETHING`, which is not how `tmpmail` currently works.

I have no knowledge of man page conventions so please do let me know my suggestions go against the man page conventions.

**Comment by GReagle** [comment]
Thank you for your feedback sdushantha.  I am glad that you like it.  I will create a fork and pull request for it.  Yes you're right about the comma separating the options.  I reworded the --text description to try to resolve the ambiguity.
