### ISSUE TITLE
Add support to GuerrillaMail

### ISSUE THREAD

**Issue by fabianski7** [sdushantha/tmpmail#38]
Many sites block the domain 1secmail.com and .net, so an alternative is needed for these cases.
GuerrillaMail also has an api and may be a good option to consider.

http://www.guerrillamail.com/GuerrillaMailAPI.html

**Comment by fabianski7** [comment]
burner.kiwi also seems to be a great alternative
https://github.com/haydenwoodhead/burner.kiwi
https://about.burner.kiwi/apidocs/

**Comment by sdushantha** [comment]
This would a great addition to `tmpmail`!
We could have a `--api API_NAME` flag where API_NAME would be either `1secmail`, `guerrillamail`, or `burner.wiki`.

But before add this feature we have to do some thinking.

GuerrillaMail and bruner.wiki both have to behave the same as 1secmail. So they should be able to take in a custom email that is provided through `--generate testing@xyz.com`, where xyz.com is of course a valid domain supported by either 1secmail, guerrillamail, or burner.wiki.

Since we are adding two more services, which behave very similar to 1secmail, but might have a few differences in terms of parameters that is required by the API, we will have to think of how we are going to add this to `tmpmail`. I really do want to keep `tmpmail` as POSIX shell script, but there is a chance that we might need to rewrite it in Python as the code would cleaner and easier to understand. Doing a rewrite in Python would also allow us to create modules for each API. 

I do want to say that this feature might not be added this year. Might be added between June and July of 2021 because I have other things to prioritize.

**Comment by fabianski7** [comment]
there are also some implementations of the GuerrillaMail API in python, like this one
https://github.com/ncjones/python-guerrillamail

**Comment by GReagle** [comment]
I wrote 3 small commands in Posix shell script that support both burner.kiwi and 1secmail.  Combined length of the 3 commands is 132 lines.  I will publish soon.  I haven't looked into GuerrillaMail yet.

**Comment by GReagle** [comment]
Here it is:  https://github.com/GReagle/tec

**Comment by sdushantha** [comment]
@fabianski7 
I did some thinking today and I have come to a decision that I won't be adding burner.kiwi or guerrillamail.com. 

Why?
- **burner.kiwi**: this service does not have the same features as 1secmail. For example, we cannot create a custom username.
- **guerrillamail**: this service seems to be very unstable. It sometimes works and sometimes doesn't. I tend to get this error very frequently:
![image](https://user-images.githubusercontent.com/27065646/99555389-895d8800-29c0-11eb-8998-e35161054ef1.png)

> Many sites block the domain 1secmail.com and .net, so an alternative is needed for these cases.

1secmail now provides more options for domains:

![Screenshot 2020-11-18 at 17 08 40](https://user-images.githubusercontent.com/27065646/99555526-b6aa3600-29c0-11eb-8799-1dc6801d8e19.png)

I hope you understand why I made the decisions I made.
If you really want a command-line tool that uses one of those service you can of course fork this repo and add support for these service if that is something you really want :)

**Comment by fabianski7** [comment]
no problems. thanks
