### ISSUE TITLE
Hi, can it receive email with attachment?

### ISSUE THREAD

**Issue by macsir** [sdushantha/tmpmail#42]
I have tested and looks like it can't.  Can we have this feature possibly? Thanks.

**Comment by sdushantha** [comment]
@macsir This is a great idea! `tmpmail` uses 1secmail's API and they actually support the ability to receive attachments. When I initially created `tmpmail`, I thought of excluding that feature because I thought nobody would use it. But it looks like people do want it :)

I'll work on adding this feature when I get some time 👍

**Comment by macsir** [comment]
Thanks, that would be great!

**Comment by mehtaarn000** [comment]
I added it in #46

**Comment by sdushantha** [comment]
This has been fix in #46
