### ISSUE TITLE
Generate address and paste it into clipboard?

### ISSUE THREAD

**Issue by ReneFroger** [sdushantha/tmpmail#51]
Would it not be useful to generate an address, and paste it into the clipboard with a flag? 

I tried it with `tmpmail -g | xclip` but it doens't oddly seem to work. Perhaps mpmail -g -c` as extra flag to paste into a clipboard (with `-c` flag)?

**Comment by sdushantha** [comment]
Hi @ReneFroger,

It's been a while since I have used Linux, but I think you are supposed to have `xclip -selection c` instead of just `xclip`. I am currently on macOS and running `tmpmail -g | pbcopy` saves the email address onto my clipboard without an issue.

Try my suggestion and let me know how it goes! 😊

**Comment by ReneFroger** [comment]
I just tried it out (sorry for my late response by the way), and it's working. Thanks!
